SELECT
    c.CLS_YYMM,
    c.PRODUCT_CD,
    c.STATUS,
    COUNT(c.CONTRACT_ID)            AS CONTRACT_CNT,
    SUM(c.CONTRACT_AMT)             AS CONTRACT_AMT_SUM,
    ROUND(AVG(c.CONTRACT_AMT), 0)   AS CONTRACT_AMT_AVG,
    COALESCE(SUM(p.PAYMENT_AMT), 0) AS PAY_AMT_SUM,
    COUNT(p.PAYMENT_ID)             AS PAY_CNT
FROM @{schema}TB_CONTRACT c
LEFT JOIN @{schema}TB_PAYMENT p
    ON c.CONTRACT_ID = p.CONTRACT_ID
GROUP BY
    c.CLS_YYMM,
    c.PRODUCT_CD,
    c.STATUS
ORDER BY
    c.CLS_YYMM,
    c.PRODUCT_CD,
    c.STATUS
