pipeline:
  stages:
  - export
  - load_local
  - transform
source:
  type: oracle
  host: ''
export:
  overwrite: false
  parallel_workers: 1
  compression: gzip
  csv_name_style: full
  csv_strip_prefix: false
  format: csv
load:
  mode: replace
target:
  type: duckdb
transform:
  on_error: stop
